#!/usr/bin/env python3

import sys

liste = []
YY = []
XX = []

def part_1(a, b):
    print("--------------------------------------------------------------------------------")
    print("        X=10    X=20    X=30    X=40    X=50    Y law")
    y = 10
    val = 0.0
    ret = 0.0
    jar = 0
    while (y <= 60):
        x = 10
        if (y == 60):
            print("X law   ", end='')
        else:
            print("Y=%d    " %(y), end='')
        while (x <= 50):
            val = ((a - x) * (b - y)) / ((5 * a - 150) * (5 * b - 150))
            ret += val
            if (y == 60):
                var_y = 0
                result = 0.0
                i = jar
                while (var_y < 5):
                    result += liste[i]
                    var_y += 1
                    i += 5
                print("%0.3f   " %(result), end='')
                jar += 1
                XX.append(result)
            else:
                liste.append(val)
                print("%0.3f   " %(val), end='')
            x += 10
        if (y == 60):
            print("1.000")
        else:
            print("%0.3f" %(ret))
            YY.append(ret)
            ret = 0.0
        y += 10

def part_2(a, b):
    print("--------------------------------------------------------------------------------")
    z = 20
    result = 0.0
    print("z       20      30      40      50      60      70      80      90      100\np(Z=z)", end='')
    while (z <= 100):
        y = 10
        val = 0.0
        ret = 0.0
        while (y <= 60):
            x = 10
            while (x <= 50):
                val = ((a - x) * (b - y)) / ((5 * a - 150) * (5 * b - 150))
                if ((x + y) == z and y < 60):
                    ret += val
                x += 10
            y += 10
        print("\t%0.3f" %(ret), end='')
        result += ret
        z += 10

def unsold(a, b):
    part_1(a, b)
    part_2(a, b)
    print("\n--------------------------------------------------------------------------------")
    exit(0)

if len(sys.argv) != 3:
    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        print("USAGE\n    ./202unsold a b\n")
        print("DESCRIPTION\n    a       constant computed from past results")
        print("    b       constant computed from past results")
    else:
        print("Bad arguments")
        exit(84)
else:
    try:
        a = int(sys.argv[1])
        b = int(sys.argv[2])
        if a <= 50 or b <= 50:
            exit(84)
        else:
            unsold(a, b)
    except ValueError:
        print("Error")
        exit(84)
