##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## printf
##

all:    NAME clean

NAME:
	$(MAKE) -C ./lib/my
clean:
	find -name "*~" -delete -o -name "#*#" -delete


fclean: clean
	rm -f $(NAME)

re:     fclean all
