##
## EPITECH PROJECT, 2020
## CNA_groundhog_2019
## File description:
## Makefile
##

RM =	rm -rf

all:	groundhog

groundhog:
		cp groundhog.py groundhog
		chmod +x groundhog

clean:
		$(RM) groundhog

fclean: clean

re: fclean all

.PHONY: all clean fclean re