#!/usr/bin/env python3

import sys
from math import *

def binomiale(d):
    i = 0
    p = d / (3600 * 8)
    n = 3500
    a = (coefi(n, i)) * (p**i) * ((1 - p)**(n - i))
    print("Binomial distribution:")
    print("%d -> %0.3f" %(i, a), end='')
    while (i < 50):
        i += 1
        if (i > 0 and (i % 5) != (0)):
            print("\t", end='')
        a = (coefi(n, i)) * (p**i) * ((1 - p)**(n - i))
        print("%d -> %0.3f" %(i, a), end='')
        if ((i + 1) % 5 == 0):
            print("")
    print("")
    print("Overload: %0.1f%%" %(d))
    print("Computation time: %0.2f ms" %(d))

def poisson(d):
    i = 0
    l = 3500 * (d / (3600 * 8))
    a = exp(-l) * pow(l, i) / factorial(i)
    print("Poisson distribution:")
    print("%d -> %0.3f" %(i, a), end='')
    while (i < 50):
        i+=1
        if (i > 0 and (i % 5) != (0)):
            print("\t", end='')
        a = exp(-l) * pow(l, i) / factorial(i)
        print("%d -> %0.3f" %(i, a), end='')
        if ((i + 1) % 5 == 0):
            print("")
    print("")
    print("Overload: %0.1f%%" %(d))
    print("Computation time: %0.2f ms" %(d))

def coefi(n, k):
    a = factorial(n)
    b = factorial(k)
    c = factorial(n - k)
    res = a // (b * c)
    return (res)

if len(sys.argv) > 3 or len(sys.argv) < 2:
    exit(84)
else:
    try:
        if len(sys.argv) == 2 and sys.argv[1] == "-h":
            print("USAGE\n    ./203hotline [n k | d]\n")
            print("DESCRIPTION\n    n         n value for the computation of C(n, k)")
            print("    k         k value for the computation of C(n, k)")
            print("    d         average duration of calls (in seconds)")
            exit(0)
        elif len(sys.argv) == 2:
            d = int(sys.argv[1])
            binomiale(d)
            print("")
            poisson(d)
            exit(0)
        elif len(sys.argv) == 3:
            n = int(sys.argv[1])
            k = int(sys.argv[2])
            print("%d-combinations of a set of size %d:\n%d" %(k, n, coefi(n, k)))
            exit(0)
    except ValueError:
        print("Error")
        exit(84)
